version: "3"

#so the docker containers that will be orchestrated
services:
  data_stream:
    build: data_stream/
    depends_on:
      - my_postgres

  my_postgres:
    image: postgres:12.6 #<-- this is literally the name of the image on DockerHub

    ports: #port-mapping
      - 5555:5432 #the port mapped to localhost:the port inside the container
      #localhost:5555 <--- the "address" of the server
      #<ip-address-of-the-container>:5432 <---- also the "address" of the server

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  my_mongodb:
    image: mongo

    ports:
      - 27017:27017

  create_students:
    build: store_students/
    depends_on:
      - my_mongodb
